name: pytest

on:
  push:
    branches: [ main ]

jobs:
  pytest-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Install ServeRest
        run: npm i serverest
      
      - name: Run ServeRest
        run: (npx serverest@latest &)

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Poetry
        uses: snok/install-poetry@v1.0.0
        with:
          virtualenvs-in-project: true  
  
      - name: Install project dependencies
        run: poetry install

      - name: Run API testing with Poetry pytest
        run: |
          source .venv/bin/activate
          poetry run pytest --variables config/config.json
